# Generated by Django 3.2.9 on 2021-12-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_equipemembro_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='telefone2',
        ),
    ]
